// src/lib/quiz/questions.easy.ts
import type { Question } from "./types";

export const easyQuestions: Question[] = [
  {
    id: "E1",
    variant: "easy",
    type: "grammar",
    topic: "articles",
    prompt: "I bought ___ new notebook yesterday.",
    options: ["a", "an", "the", "—"],
    correctIndex: 0,
    explanation: "We use 'a' before a consonant sound: a new notebook.",
  },
  {
    id: "E2",
    variant: "easy",
    type: "grammar",
    topic: "prepositions",
    prompt: "He is interested ___ learning English.",
    options: ["for", "in", "at", "on"],
    correctIndex: 1,
    explanation: "Collocation: interested in.",
  },
  {
    id: "E3",
    variant: "easy",
    type: "grammar",
    topic: "present_simple",
    prompt: "My sister ___ to school every day.",
    options: ["go", "goes", "went", "going"],
    correctIndex: 1,
    explanation: "3rd person singular in Present Simple: goes.",
  },
  {
    id: "E4",
    variant: "easy",
    type: "grammar",
    topic: "past_simple",
    prompt: "We ___ a film last night.",
    options: ["watch", "watched", "are watching", "have watched"],
    correctIndex: 1,
    explanation: "'Last night' → Past Simple: watched.",
  },
  {
    id: "E5",
    variant: "easy",
    type: "grammar",
    topic: "countable_uncountable",
    prompt: "I don’t have ___ time today.",
    options: ["many", "much", "few", "a few"],
    correctIndex: 1,
    explanation: "'Time' is uncountable → much.",
  },
  {
    id: "E6",
    variant: "easy",
    type: "grammar",
    topic: "comparatives",
    prompt: "This book is ___ than that one.",
    options: [
      "more interesting",
      "interestinger",
      "most interesting",
      "the interesting",
    ],
    correctIndex: 0,
    explanation: "Long adjective → more + adjective: more interesting.",
  },
  {
    id: "E7",
    variant: "easy",
    type: "grammar",
    topic: "modals_permission",
    prompt: "You ___ use a calculator in this part.",
    options: ["must", "can", "should", "need"],
    correctIndex: 1,
    explanation: "Permission/ability → can.",
  },
  {
    id: "E8",
    variant: "easy",
    type: "grammar",
    topic: "modals_prohibition",
    prompt: "You ___ talk during the test.",
    options: ["can", "must", "mustn’t", "should"],
    correctIndex: 2,
    explanation: "Prohibition → mustn’t.",
  },
  {
    id: "E9",
    variant: "easy",
    type: "grammar",
    topic: "there_is_are",
    prompt: "There ___ two chairs in the room.",
    options: ["is", "are", "was", "be"],
    correctIndex: 1,
    explanation: "Plural noun → There are.",
  },
  {
    id: "E10",
    variant: "easy",
    type: "grammar",
    topic: "pronouns_possessive",
    prompt: "This is my phone. It’s ___.",
    options: ["my", "mine", "me", "I"],
    correctIndex: 1,
    explanation: "Possessive pronoun without noun → mine.",
  },
  {
    id: "E11",
    variant: "easy",
    type: "grammar",
    topic: "word_order",
    prompt: "Choose the correct sentence.",
    options: [
      "Usually I am late.",
      "I am late usually.",
      "I late am usually.",
      "I usually late am.",
    ],
    correctIndex: 0,
    explanation:
      "Adverb of frequency often goes before the main verb or after 'to be'.",
  },
  {
    id: "E12",
    variant: "easy",
    type: "grammar",
    topic: "future_going_to",
    prompt: "Look at the clouds! It ___ rain.",
    options: ["is going to", "will to", "going", "go to"],
    correctIndex: 0,
    explanation: "Prediction based on evidence → be going to.",
  },

  // Vocabulary (easy)
  {
    id: "E13",
    variant: "easy",
    type: "vocab",
    topic: "meaning_clear",
    prompt: "The lesson was very ___. I understood everything.",
    options: ["clear", "noisy", "strict", "weak"],
    correctIndex: 0,
    explanation: "‘Clear’ = easy to understand.",
  },
  {
    id: "E14",
    variant: "easy",
    type: "vocab",
    topic: "collocation_pay_attention",
    prompt: "Please ___ attention to the rules.",
    options: ["do", "pay", "take", "make"],
    correctIndex: 1,
    explanation: "Collocation: pay attention.",
  },
  {
    id: "E15",
    variant: "easy",
    type: "vocab",
    topic: "phrasal_look_up",
    prompt: "Can you ___ the word in the dictionary?",
    options: ["look up", "look after", "look for", "look at"],
    correctIndex: 0,
    explanation: "‘Look up’ = search for information in a dictionary.",
  },
  {
    id: "E16",
    variant: "easy",
    type: "vocab",
    topic: "opposites",
    prompt: "The opposite of “cheap” is ___.",
    options: ["small", "expensive", "busy", "modern"],
    correctIndex: 1,
    explanation: "Opposite of cheap → expensive.",
  },
  {
    id: "E17",
    variant: "easy",
    type: "vocab",
    topic: "word_formation_difficult",
    prompt: "This exercise is not ___. It’s easy.",
    options: ["difficulty", "difficult", "difficultly", "differ"],
    correctIndex: 1,
    explanation: "We need an adjective after 'is': difficult.",
  },
  {
    id: "E18",
    variant: "easy",
    type: "vocab",
    topic: "feelings_nervous",
    prompt: "I’m ___ because I didn’t study enough.",
    options: ["nervous", "bored", "surprised", "ready"],
    correctIndex: 0,
    explanation: "If you didn’t prepare, you may feel nervous.",
  },

  // Reading (easy)
  {
    id: "E19",
    variant: "easy",
    type: "reading",
    topic: "main_idea",
    prompt:
      "Read: “Short daily practice helps you remember better than one long session a week.” What is the main idea?",
    options: [
      "Weekly study is best.",
      "Daily practice is more effective.",
      "Long sessions are the only way to learn.",
      "Practice is not needed.",
    ],
    correctIndex: 1,
    explanation: "The text compares methods and supports daily practice.",
  },
  {
    id: "E20",
    variant: "easy",
    type: "reading",
    topic: "purpose_detail",
    prompt:
      "Read: “The course includes weekly mini-tests so students get used to the exam format.” Why are mini-tests included?",
    options: [
      "To make lessons longer.",
      "To get used to the exam format.",
      "To avoid homework.",
      "To replace the teacher.",
    ],
    correctIndex: 1,
    explanation: "Mini-tests help students become familiar with the format.",
  },
];
