// src/lib/quiz/questions.medium.ts
import type { Question } from "./types";

export const mediumQuestions: Question[] = [
  // Grammar (12)
  {
    id: "M1",
    variant: "medium",
    type: "grammar",
    topic: "present_perfect",
    prompt: "I ___ this book already.",
    options: ["read", "have read", "am reading", "had read"],
    correctIndex: 1,
    explanation: "‘Already’ often goes with Present Perfect: have read.",
  },
  {
    id: "M2",
    variant: "medium",
    type: "grammar",
    topic: "past_continuous",
    prompt: "I ___ when you called me.",
    options: ["slept", "was sleeping", "have slept", "sleep"],
    correctIndex: 1,
    explanation:
      "Action in progress in the past → Past Continuous: was sleeping.",
  },
  {
    id: "M3",
    variant: "medium",
    type: "grammar",
    topic: "past_perfect",
    prompt: "By the time we arrived, the lesson ___.",
    options: ["starts", "started", "had started", "has started"],
    correctIndex: 2,
    explanation:
      "Earlier past action before another past point → Past Perfect: had started.",
  },
  {
    id: "M4",
    variant: "medium",
    type: "grammar",
    topic: "first_conditional",
    prompt: "If it ___ tomorrow, we’ll stay home.",
    options: ["rains", "rained", "will rain", "would rain"],
    correctIndex: 0,
    explanation: "1st conditional: If + Present Simple, will + verb.",
  },
  {
    id: "M5",
    variant: "medium",
    type: "grammar",
    topic: "second_conditional",
    prompt: "If I ___ more time, I would join the course.",
    options: ["have", "had", "will have", "would have"],
    correctIndex: 1,
    explanation: "2nd conditional: If + Past Simple, would + verb.",
  },
  {
    id: "M6",
    variant: "medium",
    type: "grammar",
    topic: "passive_future",
    prompt: "The new rules ___ next week.",
    options: [
      "introduce",
      "introduced",
      "will introduce",
      "will be introduced",
    ],
    correctIndex: 3,
    explanation: "Future Passive: will be + past participle.",
  },
  {
    id: "M7",
    variant: "medium",
    type: "grammar",
    topic: "infinitive_after_decide",
    prompt: "She decided ___ earlier.",
    options: ["leave", "leaving", "to leave", "left"],
    correctIndex: 2,
    explanation: "Decide + to + verb: to leave.",
  },
  {
    id: "M8",
    variant: "medium",
    type: "grammar",
    topic: "gerund_after_preposition",
    prompt: "I’m good at ___ presentations.",
    options: ["make", "making", "to make", "made"],
    correctIndex: 1,
    explanation: "After a preposition (at) we use -ing: making.",
  },
  {
    id: "M9",
    variant: "medium",
    type: "grammar",
    topic: "relative_where",
    prompt: "This is the place ___ we met.",
    options: ["which", "who", "where", "whose"],
    correctIndex: 2,
    explanation: "Place → where.",
  },
  {
    id: "M10",
    variant: "medium",
    type: "grammar",
    topic: "reported_speech_past",
    prompt: "He said he ___ busy that day.",
    options: ["is", "was", "will be", "has been"],
    correctIndex: 1,
    explanation: "Reported speech backshift: 'am' → 'was'.",
  },
  {
    id: "M11",
    variant: "medium",
    type: "grammar",
    topic: "modals_advice",
    prompt: "You ___ check your answers before submitting.",
    options: ["can", "should", "mustn’t", "may"],
    correctIndex: 1,
    explanation: "Advice → should.",
  },
  {
    id: "M12",
    variant: "medium",
    type: "grammar",
    topic: "quantifiers_much",
    prompt: "There isn’t ___ sugar left.",
    options: ["many", "much", "few", "a few"],
    correctIndex: 1,
    explanation: "Uncountable noun ‘sugar’ → much.",
  },

  // Vocabulary (6)
  {
    id: "M13",
    variant: "medium",
    type: "vocab",
    topic: "phrasal_put_off",
    prompt: "We had to ___ the meeting because of the storm.",
    options: ["put off", "put on", "put up", "put in"],
    correctIndex: 0,
    explanation: "Put off = postpone.",
  },
  {
    id: "M14",
    variant: "medium",
    type: "vocab",
    topic: "collocation_make_decision",
    prompt: "Let’s ___ a decision today.",
    options: ["do", "make", "take", "pay"],
    correctIndex: 1,
    explanation: "Collocation: make a decision.",
  },
  {
    id: "M15",
    variant: "medium",
    type: "vocab",
    topic: "word_formation_concentration",
    prompt: "This task requires ___.",
    options: ["concentrate", "concentration", "concentrated", "concentrative"],
    correctIndex: 1,
    explanation: "Requires + noun: concentration.",
  },
  {
    id: "M16",
    variant: "medium",
    type: "vocab",
    topic: "meaning_delighted",
    prompt: "He was ___ to hear he passed the test.",
    options: ["worried", "delighted", "ashamed", "confused"],
    correctIndex: 1,
    explanation: "Delighted = very happy.",
  },
  {
    id: "M17",
    variant: "medium",
    type: "vocab",
    topic: "synonym_improve",
    prompt: "“Improve” is closest to:",
    options: ["make better", "make smaller", "make slower", "make cheaper"],
    correctIndex: 0,
    explanation: "Improve = make better.",
  },
  {
    id: "M18",
    variant: "medium",
    type: "vocab",
    topic: "meaning_clarification",
    prompt: "The instructions were unclear, so I asked for ___.",
    options: ["permission", "clarification", "celebration", "relaxation"],
    correctIndex: 1,
    explanation: "Clarification = making something clearer.",
  },

  // Reading (2)
  {
    id: "M19",
    variant: "medium",
    type: "reading",
    topic: "inference_planning",
    prompt:
      "Read: “Many students avoid practice tests because they fear a low score. But early low scores show what to improve.” What does the text suggest?",
    options: [
      "Avoid practice tests to stay confident.",
      "Low scores are useless.",
      "Early low scores can help you plan better.",
      "Only strong students should take tests.",
    ],
    correctIndex: 2,
    explanation:
      "The text says early low scores show what to improve and help planning.",
  },
  {
    id: "M20",
    variant: "medium",
    type: "reading",
    topic: "purpose_review",
    prompt:
      "Read: “We review mistakes right after each mini-test to prevent repeating them.” Why review mistakes immediately?",
    options: [
      "To finish the lesson faster.",
      "To avoid repeating the same mistakes.",
      "To make the test harder next time.",
      "To reduce homework completely.",
    ],
    correctIndex: 1,
    explanation: "Immediate review helps prevent repeating mistakes.",
  },
];
