// src/lib/quiz/questions.hard.ts
import type { Question } from "./types";

export const hardQuestions: Question[] = [
  // Grammar (12)
  {
    id: "H1",
    variant: "hard",
    type: "grammar",
    topic: "third_conditional",
    prompt: "If she ___ earlier, she would have caught the bus.",
    options: ["leaves", "left", "had left", "would leave"],
    correctIndex: 2,
    explanation: "3rd conditional: If + Past Perfect, would have + V3.",
  },
  {
    id: "H2",
    variant: "hard",
    type: "grammar",
    topic: "mixed_conditional",
    prompt: "If I had studied more, I ___ more confident now.",
    options: ["am", "would be", "will be", "had been"],
    correctIndex: 1,
    explanation: "Past condition → present result: would be now.",
  },
  {
    id: "H3",
    variant: "hard",
    type: "grammar",
    topic: "reported_speech_past_perfect",
    prompt: "He said he ___ the email the day before.",
    options: ["sends", "sent", "had sent", "has sent"],
    correctIndex: 2,
    explanation: "Reported speech: Past Simple often shifts to Past Perfect.",
  },
  {
    id: "H4",
    variant: "hard",
    type: "grammar",
    topic: "modals_deduction",
    prompt: "She isn’t answering. She ___ be in a meeting.",
    options: ["must", "should", "can’t", "need"],
    correctIndex: 0,
    explanation: "Strong deduction → must.",
  },
  {
    id: "H5",
    variant: "hard",
    type: "grammar",
    topic: "modals_impossibility",
    prompt: "That ___ be true — it doesn’t match the data.",
    options: ["must", "might", "can’t", "should"],
    correctIndex: 2,
    explanation: "Impossibility/strong negative deduction → can’t.",
  },
  {
    id: "H6",
    variant: "hard",
    type: "grammar",
    topic: "inversion_not_only",
    prompt: "Not only ___ late, but he also forgot the documents.",
    options: ["he arrived", "did he arrive", "he did arrive", "arrived he"],
    correctIndex: 1,
    explanation:
      "Inversion after 'Not only' → auxiliary before subject: did he arrive.",
  },
  {
    id: "H7",
    variant: "hard",
    type: "grammar",
    topic: "relative_whose",
    prompt: "She’s the student ___ project won the prize.",
    options: ["who", "whose", "which", "where"],
    correctIndex: 1,
    explanation: "Possession → whose project.",
  },
  {
    id: "H8",
    variant: "hard",
    type: "grammar",
    topic: "reduced_relative",
    prompt: "Students ___ late won’t be allowed to enter.",
    options: ["arrive", "arriving", "to arrive", "arrived"],
    correctIndex: 1,
    explanation: "Reduced relative clause: students arriving late.",
  },
  {
    id: "H9",
    variant: "hard",
    type: "grammar",
    topic: "passive_past_perfect",
    prompt: "The report ___ by 5 pm yesterday.",
    options: [
      "finished",
      "was finished",
      "has been finished",
      "had been finished",
    ],
    correctIndex: 3,
    explanation: "Past perfect passive: had been + V3.",
  },
  {
    id: "H10",
    variant: "hard",
    type: "grammar",
    topic: "future_perfect",
    prompt: "By next month, I ___ the whole course.",
    options: ["finish", "will finish", "will have finished", "have finished"],
    correctIndex: 2,
    explanation:
      "Future Perfect for completion before a future time: will have finished.",
  },
  {
    id: "H11",
    variant: "hard",
    type: "grammar",
    topic: "gerund_stop",
    prompt: "I stopped ___ because it was too noisy.",
    options: ["study", "studying", "to study", "studied"],
    correctIndex: 1,
    explanation: "Stop doing something = stop the activity → stopped studying.",
  },
  {
    id: "H12",
    variant: "hard",
    type: "grammar",
    topic: "articles_information",
    prompt: "___ information you gave me was very helpful.",
    options: ["A", "An", "The", "—"],
    correctIndex: 2,
    explanation:
      "Specific information (the one you gave me) → The information.",
  },

  // Vocabulary (6)
  {
    id: "H13",
    variant: "hard",
    type: "vocab",
    topic: "collocation_have_impact",
    prompt: "The new policy will ___ an impact on results.",
    options: ["do", "make", "have", "give"],
    correctIndex: 2,
    explanation: "Collocation: have an impact.",
  },
  {
    id: "H14",
    variant: "hard",
    type: "vocab",
    topic: "phrasal_turn_down",
    prompt: "She ___ the offer because the conditions were unclear.",
    options: ["turned down", "took off", "put out", "ran into"],
    correctIndex: 0,
    explanation: "Turn down = refuse.",
  },
  {
    id: "H15",
    variant: "hard",
    type: "vocab",
    topic: "word_formation_unrealistic",
    prompt: "It’s ___ to expect perfect results in one week.",
    options: ["realistic", "unreal", "unrealistic", "reality"],
    correctIndex: 2,
    explanation: "Meaning needed: not realistic → unrealistic.",
  },
  {
    id: "H16",
    variant: "hard",
    type: "vocab",
    topic: "meaning_breaking_rules",
    prompt: "He was accused of ___ the rules during the exam.",
    options: ["breaking", "damaging", "losing", "missing"],
    correctIndex: 0,
    explanation: "Break rules = violate rules.",
  },
  {
    id: "H17",
    variant: "hard",
    type: "vocab",
    topic: "linking_word_however",
    prompt: "He studied hard; ___, he didn’t pass.",
    options: ["therefore", "however", "because", "besides"],
    correctIndex: 1,
    explanation: "Contrast → however.",
  },
  {
    id: "H18",
    variant: "hard",
    type: "vocab",
    topic: "meaning_adapted",
    prompt: "The plan is flexible and can be ___ to your schedule.",
    options: ["adapted", "avoided", "delayed", "imagined"],
    correctIndex: 0,
    explanation: "Adapted = changed to fit.",
  },

  // Reading (2)
  {
    id: "H19",
    variant: "hard",
    type: "reading",
    topic: "reading_strategy_scanning",
    prompt:
      "Read: “Some learners translate every word. This slows them down. Training scanning skills helps find key information faster.” What is recommended?",
    options: [
      "Translate every word while reading.",
      "Practice scanning to find key information.",
      "Read more slowly to understand better.",
      "Avoid reading tasks completely.",
    ],
    correctIndex: 1,
    explanation: "The text recommends scanning for key information.",
  },
  {
    id: "H20",
    variant: "hard",
    type: "reading",
    topic: "purpose_mock_tests",
    prompt:
      "Read: “Weekly mock tests reduce stress by making the exam format familiar.” Why do mock tests reduce stress?",
    options: [
      "They replace lessons.",
      "They make the format familiar.",
      "They remove the need for homework.",
      "They lower the difficulty of the exam.",
    ],
    correctIndex: 1,
    explanation: "Familiarity with format → less stress.",
  },
];
